# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Bomane' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Bomane
  pod 'Alamofire', '~> 4.0'
  pod 'PopupDialog', '~> 0.5'
  pod 'SwiftyJSON', '~> 3.1'
  pod 'Kingfisher', '~> 3.1'
  pod 'FacebookCore'
  pod 'FacebookLogin'
  pod 'FacebookShare'
  pod 'ReachabilitySwift', '~> 3'
  pod 'SwiftMessages'

end
